pool:
    vmImage: 'ubuntu-latest'

steps:
    - task: UsePythonVersion@0
      inputs:
          versionSpec: '>=3.5'
    - script: |
        set -x
        sudo apt update
        sudo apt install -y qemu-user git-lfs
        python -m pip install --upgrade pip
        pip install pytest wheel
      displayName: Install dependencies

    - script: |
        git lfs pull
      displayName: Pull prebuilt binaries

    - script: |
        pytest
      displayName: Run tests

    - script: |
        python setup.py sdist bdist_wheel
