pool:
    vmImage: 'ubuntu-latest'

steps:
    - task: UsePythonVersion@0
      inputs:
          versionSpec: '>=3.5'
    - script: |
        sudo apt install qemu-user
        python -m pip install --upgrade pip
        pip install pytest wheel
      displayName: Install dependencies

    - script: |
        pytest
      displayName: Run tests

    - script: |
        python setup.py sdist bdist_wheel
